import { Lock, Cpu, TrendingUp, ShieldCheck, MapPin, Scale, Search, Award, Calculator, Users, Wrench, Star, Zap, Building2 } from 'lucide-react';

/* ─── Buyer Plans ─── */
export const BUYER_PLANS = [
  {
    id: 'free',
    name: 'Free',
    emoji: '🆓',
    tagline: '정보의 민주화',
    price: '무료',
    priceNote: '영구 무료',
    coreValue: '아날로그 발품 → 디지털 투명 정보로 전환',
    painKilled: '카탈로그·영업멘트 기반의 불투명한 시장',
    shieldAgents: ['H'],
    color: 'slate',
    features: [
      { text: 'SI 업체 검색·필터 (지역·업종·규모)', included: true },
      { text: '제조사 인증 뱃지 확인', included: true },
      { text: '평판·재무 뷰어 일부 열람', included: true },
      { text: '안심 에스크로 결제', included: false },
      { text: '24h 긴급 출동 보증', included: false },
      { text: 'RaaS 금융 연계', included: false },
    ],
    cta: '무료로 탐색 시작',
    ctaLink: '/signup/buyer',
  },
  {
    id: 'care',
    name: 'Care',
    emoji: '🛡️',
    tagline: '리스크의 완전한 외부 전가',
    price: '보증료 5~10%',
    priceNote: '계약 금액 기준',
    coreValue: '도입 전·중·후 모든 리스크를 플랫폼이 전담',
    painKilled: '"SI 부도나면 내 목이 날아감" 공포 원천 차단',
    shieldAgents: ['E', 'L', 'D'],
    color: 'blue',
    badge: '가장 인기',
    features: [
      { text: 'SI 업체 검색·필터 전체', included: true },
      { text: '평판·재무 뷰어 전체 열람', included: true },
      { text: '안심 에스크로 결제 (계약금 100% 보호)', included: true },
      { text: '24h 긴급 출동 보증 + 대체 시공', included: true },
      { text: '블록체인 AS 보증서 발급', included: true },
      { text: 'O2O 현장 매니저 예약', included: true },
    ],
    cta: 'Care 플랜 사전 예약',
    ctaLink: '/signup/buyer',
  },
  {
    id: 'finance',
    name: 'Finance',
    emoji: '💰',
    tagline: '자본 효율의 극대화',
    price: 'Care + 금융 쉐어 1.5~2%',
    priceNote: 'RaaS 전환 수익 공유',
    coreValue: 'CAPEX 장벽을 월 구독(OPEX)으로 허물어 즉시 도입 가능',
    painKilled: 'SME 44.2%의 "목돈 부담" 도입 주저',
    shieldAgents: ['I', 'E', 'L', 'D'],
    color: 'emerald',
    features: [
      { text: 'Care 플랜 전체 포함', included: true },
      { text: 'OPEX 비용 계산기 (월 ~100만 원 시뮬레이션)', included: true },
      { text: '캐피탈·리스 금융사 연계 (36개월 분할)', included: true },
      { text: 'RaaS 구독 전환 신청', included: true },
      { text: '전담 금융 컨설턴트 배정', included: true },
      { text: '정부 보조금 신청 가이드 제공', included: true },
    ],
    cta: 'Finance 플랜 대기 등록',
    ctaLink: '/signup/buyer',
  },
];

/* ─── Seller Plans ─── */
export const SELLER_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    emoji: '📌',
    tagline: '온라인 존재감의 시작',
    price: '무료',
    priceNote: '영구 무료',
    coreValue: '연 매출 10억 이하 영세 SI의 유일한 온라인 판로',
    painKilled: '박람회·지인 소개에만 의존하는 파편화된 영업',
    color: 'slate',
    features: [
      { text: '기본 프로필 등록', included: true },
      { text: '시공 레퍼런스 DB 최대 3건', included: true },
      { text: '제조사 인증 뱃지 노출', included: false },
      { text: '메인 상단 노출', included: false },
      { text: '인바운드 리드 배분', included: false },
      { text: '전담 계정 매니저', included: false },
    ],
    cta: '무료로 등록 시작',
    ctaLink: '/signup/partner',
  },
  {
    id: 'pro',
    name: 'Pro',
    emoji: '🚀',
    tagline: '검증된 업체 브랜딩 + 리드 우선 배분',
    price: '월 20만 원',
    priceNote: '연간 결제 시 할인',
    coreValue: '무보수 선행 컨설팅 낭비 → 인바운드 리드로 대체',
    painKilled: '무보수 가설계에 소모되는 인적 자원 낭비',
    color: 'blue',
    badge: '추천',
    features: [
      { text: '레퍼런스 DB 무제한 등록', included: true },
      { text: '제조사 인증 뱃지 노출', included: true },
      { text: '메인 상단 우선 노출', included: true },
      { text: '3D 시뮬레이션 VOD 무제한 업로드', included: true },
      { text: '인바운드 리드 우선 배분', included: true },
      { text: '전담 계정 매니저', included: false },
    ],
    cta: 'Pro 플랜 시작하기',
    ctaLink: '/signup/partner',
  },
  {
    id: 'business',
    name: 'Business',
    emoji: '💎',
    tagline: '제조사 공식 VIP 파트너 격상',
    price: '협의',
    priceNote: '전담 매니저 직접 상담',
    coreValue: '단순 SI 업체 → 제조사 공인 VIP 파트너 브랜드 레벨업',
    painKilled: '브랜드 인지도 없어 수주 경쟁에서 밀리는 구조',
    color: 'amber',
    features: [
      { text: 'Pro 플랜 전체 포함', included: true },
      { text: '인바운드 리드 전용 배분 (경쟁 없음)', included: true },
      { text: '제조사 공식 파트너 등록 (VIP 격상)', included: true },
      { text: '전담 계정 매니저 1:1 배정', included: true },
      { text: '제조사 공동 B2B 제안 참여권', included: true },
      { text: '최우수 SI 대상 리드 무료 제공', included: true },
    ],
    cta: 'Business 상담 신청',
    ctaLink: '/signup/partner',
  },
];


/* ─── S.H.I.E.L.D. 6 Agents ─── */
export const SHIELD_AGENTS = [
  {
    letter: 'S',
    code: 'Solvency AI',
    title: '재무 리스크 감시',
    subtitle: '"이 업체가 계약금만 받고 도망갈 확률은 0%인가?"',
    desc: 'SI 업체의 신용등급·자본 흐름·파산 리스크를 실시간 스크리닝. 재무 위험 징후 발생 시 즉시 에스크로 자금 동결 및 알림.',
    icon: TrendingUp,
    color: 'red',
    persona: '조상필 대표 Pain 해소',
  },
  {
    letter: 'H',
    code: 'Hardware & Tech AI',
    title: '기술 적합성 검증',
    subtitle: '"이 업체가 우리 공장과 같은 걸 성공해 본 적 있는가?"',
    desc: '과거 시공 레퍼런스와 고객 공정의 Fit을 분석. 납기율·성공률·실패율을 수치로 공개해 영업 멘트가 아닌 데이터로 판단.',
    icon: Cpu,
    color: 'blue',
    persona: '김도진 팀장 Pain 해소',
  },
  {
    letter: 'I',
    code: 'Investment ROI AI',
    title: '투자 효율 분석',
    subtitle: '"3천만 원 일시불 vs 월 구독, 어느 것이 진짜 이득인가?"',
    desc: 'CAPEX·리스·RaaS(월~100만 원) 3가지 옵션을 공정별 ROI로 즉시 비교. 현금 흐름 부담 없이 최적 투자 방식 선택.',
    icon: TrendingUp,
    color: 'amber',
    persona: '초기 CAPEX 부담 해소',
  },
  {
    letter: 'E',
    code: 'Escrow Execution AI',
    title: '에스크로 자금 통제',
    subtitle: '"내 돈이 약속을 지켰을 때만 지급되는가?"',
    desc: '계약금 100% 락업(Lock-up). 시공 단계별 검수가 완벽히 끝났을 때만 자금 해제. SI 파산 시 전액 자동 환불 집행.',
    icon: Lock,
    color: 'emerald',
    persona: '계약 파기 리스크 제로화',
  },
  {
    letter: 'L',
    code: 'Local A/S AI',
    title: '로컬 유지보수 관제',
    subtitle: '"고장 시 24시간 안에 수리기사가 무조건 오는가?"',
    desc: '전국 제조사 인증 파트너망 실시간 추적. 고장 접수 즉시 반경 50km 내 최적 엔지니어 자동 출동 명령. SI 파산 후에도 유지.',
    icon: MapPin,
    color: 'purple',
    persona: '고철 방치 트라우마 원천 차단',
  },
  {
    letter: 'D',
    code: 'Dispute Resolution AI',
    title: '분쟁 징후 예측',
    subtitle: '"싸움이 나기 전에 플랫폼이 먼저 개입하는가?"',
    desc: '커뮤니케이션 로그·진척도 데이터를 분석해 납기 지연·분쟁 징후 조기 감지. 징후 발생 시 O2O 휴먼 컨설턴트 선제 파견.',
    icon: Scale,
    color: 'slate',
    persona: '소통 단절·시공 지연 스트레스 해소',
  },
];

/* ─── Hero Stats ─── */
export const HERO_STATS = [
  { value: 100, suffix: '%', label: '계약금 에스크로 보호', highlight: false },
  { value: 50, suffix: 'km', label: '로컬 AS 출동 반경', highlight: false },
  { value: 24, suffix: 'h', label: '긴급 출동 보장', highlight: false },
  { value: 0, suffix: '%', label: '도입 실패 리스크', highlight: true },
];

/* ─── Real Quotes ─── */
export const PAIN_QUOTES = [
  { quote: '내 돈 3천만 원이 고철덩어리가 됐어', name: '조상필', role: '영세 제조업 대표', aos: 'P9 — Importance 5.0 / Satisfaction 1.0' },
  { quote: '기안 올릴 때 이 업체가 부도나면 누가 책임지나 하는 압박감이 큽니다', name: '김도진', role: '중견기업 생산기술 팀장', aos: 'P1 — Importance 4.8 / Satisfaction 2.0' },
];

/* ─── Market Stats ─── */
export const MARKET_STATS = [
  { value: '7조 원', label: '국내 로봇 시장 규모 (2024)' },
  { value: '1위', label: '세계 로봇 밀도 (1,012대/만 명)' },
  { value: '5.8배', label: '경쟁사 마로솔 1년 성장 (9억→51억)' },
  { value: '44.2%', label: 'CAPEX 부담으로 도입 주저 SME' },
];

/* ─── 3 Persona CTAs ─── */
export const PERSONA_CTAS = [
  {
    persona: '조상필 대표님께',
    badge: '🔴 Primary CTA — 극단 사용자',
    title: '지금 사전 예약하기',
    subtitle: '무한 AS 보증 1호 파트너 선점',
    desc: '출시 전 S.H.I.E.L.D. 보호 서비스 우선 배정 + 에스크로 보증료 20% 할인 쿠폰 즉시 발급.',
    fields: '회사명 / 담당자 연락처 / 도입 예정 로봇 유형',
    color: 'red',
    link: '/home',
  },
  {
    persona: '김도진 팀장님께',
    badge: '🔵 Secondary CTA — 기안 담당자',
    title: '업종 맞춤 SI 알림 설정',
    subtitle: '기안용 레퍼런스 리포트 자동 발송 (PDF 1-Click)',
    desc: '업종·지역·로봇 브랜드 선택 시, 조건 맞는 SI 신규 등록 즉시 알림 + H.AI 검증 리포트 자동 발송.',
    fields: '업종 / 지역 / 선호 로봇 브랜드',
    color: 'blue',
    link: '/home',
  },
  {
    persona: '강혁진 영업팀장님께',
    badge: '⚫ Nurturing CTA — 파트너/제조사',
    title: '파트너 인증 대기 리스트 등록',
    subtitle: '정식 오픈 시 얼리버드 혜택 우선 안내',
    desc: 'SI 업체·로봇 제조사·도입 희망 기업 구분 선택 → 역할별 온보딩 가이드 + S.H.I.E.L.D. 파트너십 우선 협의.',
    fields: '회사 유형 / 회사명 / 연락처',
    color: 'slate',
    link: '/home',
  },
];
